

#pragma once

#include "NativeGameplayTags.h"

namespace PokemonDebugTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debug);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Decision);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_State);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Knockback);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_Faint);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Addition);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Activation);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cooldown);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Targeting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Targeting_Trace);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Spawn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Impact);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Network);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Network_RPC);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Transition);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Log);
}
